FROM ubuntu:22.04@sha256:0e5e4a57c2499249aafc3b40fcd541e9a456aab7296681a3994d631587203f97

# Environment variables
#######################

ENV DEBIAN_FRONTEND noninteractive
ENV USER root

# Install dependencies
RUN /workdir/.ci_scripts/install-build-rootfs-14-dependencies.sh

# Set the work directory
########################
WORKDIR /workdir

# Allow redirection of stdout to docker logs
############################################
RUN ln -sf /proc/1/fd/1 /var/log/docker.log

# Set the entry point to bash
################################
CMD ["/bin/bash"]
